version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: scrumify-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: scrumify
    ports:
      - "18343:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
