spring.application.name=scrumify
spring.datasource.url=jdbc:postgresql://localhost:18343/scrumify?currentSchema=scrumify
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.locations=classpath:db/setup,classpath:db/migration
logging.level.root=info
server.port=17003
